package sos.scheduler.editor.classes;

import org.eclipse.swt.widgets.Combo;
import org.eclipse.swt.widgets.Composite;

/**
* \class LanguageSelector 
* 
* \brief LanguageSelector - 
* 
* \details
*
* \section LanguageSelector.java_intro_sec Introduction
*
* \section LanguageSelector.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 25.08.2011
* \see reference
*
* Created on 25.08.2011 13:54:32
 */

public class LanguageSelector extends Combo {

	@SuppressWarnings("unused")
	private final String	conClassName	= "LanguageSelector";

	public LanguageSelector(Composite arg0, int arg1) {
		super(arg0, arg1);
	}
	
    public void selectLanguageItem(int languageId) {
    	this.select(languageId);
    }
	
	public boolean isJava (){
		return this.getText().equalsIgnoreCase("java");
	}
	
	public boolean isShell (){
		return this.getText().equalsIgnoreCase("shell");
	}
	
	protected void checkSubclass() {
		// Disable the check that prevents subclassing of SWT components
		} 
}
